services:
  postgres13:
    image: postgres:13.21-alpine3.21
    container_name: code-live-execution-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: code_live_execution
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:7-alpine"
    container_name: code-live-execution-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: code-live-execution-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"
  api:
    build: .
    container_name: code-live-execution-api
    entrypoint:
      [
        "./wait-for-it.sh",
        "postgres13:5432",
        "--",
        "./wait-for-it.sh",
        "redis:6379",
        "--",
        "node",
        "dist/main.js",
      ]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://root:secret@postgres13:5432/code_live_execution
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  redisdata:
  pgdata:
