services:
  postgres13:
    image: postgres:13.21-alpine3.21
    container_name: code-live-execution-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: code_live_execution
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:7-alpine"
    container_name: code-live-execution-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: code-live-execution-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"

volumes:
  redisdata:
  pgdata:
